Repository uni-helper/vite-plugin-uni-components, pull requests merged in 2024-08, with the labels that each got.

#9 fix: vue version check
  packages/core/src/declaration.ts
Labels: size/XS

#11 fix: augment `vue` rather than `@vue/runtime-core`
  README.md
  playground/components.d.ts
  test/__snapshots__/dts.test.ts.snap
  test/dts.test.ts
Labels: size/S

#12 feat: support uv-ui resolver
  README.md
  packages/core/src/_resolvers/index.ts
  packages/core/src/_resolvers/uv-ui.ts
  playground/components.d.ts
  playground/package.json
  playground/src/pages/index/index.vue
  playground/vite.config.ts
  pnpm-lock.yaml
Labels: size/M
